create table BCF_APPLICATIONS
(
APPLICATION_ID NUMBER,
APPLICATION_NAME VARCHAR2(100),
APPLICATION_DESCRIPTION VARCHAR2(1000),
APPLICATION_PARALLELISM NUMBER,
APPLICATION_WAIT_TIME NUMBER,
APPLICATION_WAIT_REPETITION NUMBER
)
/

create table BCF_APPLICATION_JOBS
(
APPLICATION_ID NUMBER,
JOB_ID NUMBER,
JOB_COMMAND VARCHAR2(1000), -- datastage job name
JOB_PARAMETERS VARCHAR2(1000), -- format datastage : Param1=Value1|Param2=Value2
JOB_DESCRIPTION VARCHAR2(1000),
JOB_ORDER NUMBER,
JOB_TYPE varchar2(100) -- DSJOB, SCRIPT
)
/

create table BCF_APPLICATION_STATUS
(
APPLICATION_ID NUMBER,
APPLICATION_NAME VARCHAR2(100),
START_TIME DATE,
END_TIME DATE,
STATUS VARCHAR2(100) --RUNNING	
)
/

create table BCF_APPLICATION_STATUS_HISTORY
(
APPLICATION_STATUS_ID NUMBER,
APPLICATION_ID NUMBER,
APPLICATION_NAME VARCHAR2(100),
START_TIME DATE,
END_TIME DATE,
STATUS VARCHAR2(100)
)
/

create table BCF_JOB_STATUS
(
APPLICATION_ID NUMBER,
JOB_ID NUMBER,
JOB_COMMAND VARCHAR2(1000),
JOB_PARAMETERS VARCHAR2(1000),
JOB_ORDER NUMBER,
JOB_TYPE varchar2(100),
START_TIME DATE,
END_TIME DATE,
STATUS VARCHAR2(100) --QUEUED, FAIL, RUNNING, SUCCESS
)
/

create table BCF_JOB_STATUS_HISTORY
(
JOB_STATUS_ID NUMBER,
APPLICATION_ID NUMBER,
JOB_ID NUMBER,
JOB_COMMAND VARCHAR2(1000),
JOB_PARAMETERS VARCHAR2(1000),
JOB_ORDER NUMBER,
JOB_TYPE varchar2(100),
START_TIME DATE,
END_TIME DATE,
STATUS VARCHAR2(100) --QUEUED, FAIL, RUNNING, SUCCESS
)
/

create table BCF_SCHEDULER
(
APPLICATION_ID NUMBER,
SCHEDULE_TYPE VARCHAR2(100), -- DAILY, WEEKLY, MONTHLY, EVERY
SCHEDULE_TIME VARCHAR2(10), --  DAILY, WEEKLY, MONTHLY - 14:00, EVERY - 10 (minutes)
COMMENTS varchar2(1000)
)

CREATE SEQUENCE SEQ_APPLICATION_STATUS_ID
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  START WITH 1
  INCREMENT BY 1
  CACHE 20;
  
CREATE SEQUENCE SEQ_JOB_STATUS_ID
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  START WITH 1
  INCREMENT BY 1
  CACHE 20;